Repository pactus-project/pactus, pull requests merged in 2023-09, with the labels that each got.

#670 chore: fix unbond typo
  execution/execution.go
  state/mock.go
  state/state.go
  state/state_test.go
  txpool/pool.go
  types/tx/payload/payload.go
  types/tx/payload/unbond.go
  types/tx/tx.go
  wallet/tx_builder.go
  wallet/wallet.go
  www/grpc/transaction.go
Labels: enhancement

#671 feat: implementing pip-0004 `indexing public key`
  consensus/propose_test.go
  execution/execution_test.go
  sandbox/sandbox_test.go
  state/facade.go
  state/lastinfo/last_info.go
  state/lastinfo/last_info_test.go
  state/mock.go
  state/state.go
  state/state_test.go
  store/block.go
  store/block_test.go
  store/errors.go
  store/interface.go
  store/mock.go
  store/store.go
  store/store_test.go
  sync/bundle/bundle_test.go
  sync/bundle/message/block_announce_test.go
  sync/bundle/message/blocks_response.go
  sync/bundle/message/blocks_response_test.go
  sync/cache/cache_test.go
  sync/handler_block_announce_test.go
  sync/handler_blocks_request.go
  sync/handler_blocks_request_test.go
  sync/handler_blocks_response.go
  sync/handler_blocks_response_test.go
  sync/sync.go
  sync/sync_test.go
  types/account/account_test.go
  types/block/block.go
  types/block/block_test.go
  types/block/errors.go
  types/block/header.go
  types/certificate/certificate_test.go
  types/tx/errors.go
  types/tx/tx.go
  types/tx/tx_test.go
  types/validator/validator_test.go
  util/testsuite/testsuite.go
  util/utils.go
  www/grpc/blockchain.go
  www/grpc/blockchain_test.go
  www/grpc/transaction.go
  www/grpc/transaction_test.go
Labels: Breaking Changes

#683 feat: check protocol support before sending connect/disconnect event
  network/mdns_test.go
  network/network.go
  network/notifee.go
Labels: bug, p2p

#697 feat: Adding Hole Punching to network
  network/network.go
Labels: p2p

#702 feat: CreateValidatorEvent and CreateAccountEvent for nanomsg
  state/state.go
  types/tx/payload/bond.go
  types/tx/payload/payload.go
  types/tx/payload/sortition.go
  types/tx/payload/transfer.go
  types/tx/payload/unbond.go
  types/tx/payload/withdraw.go
  types/tx/tx.go
  www/nanomsg/event/event.go
  www/nanomsg/event/event_test.go
Labels: www, high priority

#705 test: fixing a broken test
  txpool/pool_test.go
Labels: bug, CI/CD

#707 chore(lint): enable nonamedreturns linter
  .gitignore
  .golangci.yml
  cmd/cmd.go
  committee/committee.go
  sortition/vrf.go
  state/state.go
  util/io.go
Labels: CI/CD, Linting
