Repository pactus-project/pactus, pull requests merged in 2023-08, with the labels that each got.

#653 chore: enable thelper linter
  .golangci.yml
  consensus/consensus_test.go
  consensus/voteset/voteset_test.go
  execution/executor/transfer_test.go
  network/network_test.go
  sandbox/sandbox_test.go
  state/lastinfo/last_info_test.go
  state/state_test.go
  store/store_test.go
  sync/firewall/firewall_test.go
  sync/sync_test.go
  tests/account_test.go
  tests/transaction_test.go
  tests/validator_test.go
  txpool/pool_test.go
  util/testsuite/testsuite.go
  wallet/vault/vault_test.go
  wallet/wallet_test.go
  www/grpc/server_test.go
  www/http/http_test.go
Labels: enhancement

#662 chore: enable wastedassign linter
  .golangci.yml
  cmd/daemon/init.go
  cmd/gtk/utils.go
  wallet/encrypter/encrypter.go
  wallet/wallet.go
Labels: enhancement, CI/CD, Linting

#667 refactor(committee): using generic list for validators
  committee/committee.go
  txpool/pool.go
  util/linkedlist/linkedlist.go
  util/linkedlist/linkedlist_test.go
  util/linkedmap/linkedmap.go
Labels: enhancement, consensus

#665 refactor: change Hello message from broadcasting to direct messaging
  network/notifee.go
  sync/handler_blocks_request.go
  sync/handler_blocks_response_test.go
  sync/handler_hello.go
  sync/handler_hello_test.go
  sync/peerset/peer.go
  sync/peerset/peer_set_test.go
  sync/peerset/peer_test.go
  sync/peerset/status_code.go
  sync/sync.go
  sync/sync_test.go
Labels: p2p
